name: "Hello World"
on: 
  pull_request:
     branches: 
       - main
  push:
jobs:
  Hello-world:
    strategy:
      matrix:
        name: [ubuntu-latest]
    runs-on: ${{ matrix.name }}
    steps:
      - name: hello world
        run: |
         echo "Hello Prem"
         echo "hello jeeva"
         echo "hello ${{ vars.MY_NAME }}"
         name = ${{secrets.MY_NAME}}
         echo $name
    
