name: "Hello World"
on: 
  pull_request:
     branches: 
       - main
jobs:
  Hello-world:
    strategy:
      matrix:
        name: [ubuntu-latest]
    runs-on: ${{ matrix.name }}
    steps:
      - name: hello world
        run: |
         echo "Hello Prem"
         echo "hello jeeva"
    
